service: serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256
        
functions:
  status:
    handler: src/lambda/hello.handle
    events:
      - http:
          path: /
          method: get
  create_user:
    handler: src/lambda/users.create
    events:
      - http:
          path: users
          method: post

plugins:
  - serverless-offline
