service: serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: sa-east-1
  memorySize: 256
        
functions:
  helloworld:
    handler: src/lambda/helloworld.handle

plugins:
  - serverless-offline
